[tool.poetry]
name = "redisenv"
version = "0.1.0"
description = ""
authors = ["Redis OSS <oss@redis.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
