name: IntegrationA

on:
  pull_request:

jobs:
  build_and_test:
    name: Test
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: install dependencies
        run: |
          pip install --upgrade pip setuptools poetry
          poetry config virtualenvs.create false
          poetry install

      - name: cache
        uses: actions/cache@v3
        with:
          key: ${{runner.os }}-pip-${{hashFiles('pyproject.toml')}}
          restore-keys: |
            ${{runner.os}}-pip-
          path: |
            ~/.pip
            ~/.cache/pip
            ~/.cache/poetry

      - name: run tests
        run: |
          pytest

      - name: build package
        run: |
          poetry build