name: Linting

on:
  pull_request:

jobs:

  lint:
    name: Code linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install python
        uses: actions/setup-python@v4
      - name: poetry
        run: |
          pip install --upgrade pip setuptools poetry
          poetry config virtualenvs.create false
          poetry install
      - name: cache
        uses: actions/cache@v3
        with:
          key: ${{runner.os }}-pip-${{hashFiles('pyproject.toml')}}
          restore-keys: |
            ${{runner.os}}-pip-
          path: |
            ~/.pip
            ~/.cache/pip
            ~/.cache/poetry
      - name: lint
        run: |
          invoke linters